### ISSUE TITLE
2 different projects, both error on the first run

### ISSUE THREAD

**Issue by Hustler-Am-Limit** [bloggrify/bloggrify#1]
Hi there, I really like this template.

However I noticed that when I clone this (bloggrify) repo, run npm install and npm run dev, I get an error saying that I need the mistral theme: _Invalid layout `themes-mistral-default` selected._

So I cloned the bloggrify-mistral repo into another seperate folder, ran npm install and npm run dev, and I got an error with catppuccin, which I could fix but I ask myself: Why are there 2 different repos and which one should I clone?

Thanks, I am considering donating to this project.

**Comment by Nevsy** [comment]
Same over here. You can contact me for more information if necessary.
Thanks in advance,
Nevsy

**Comment by hlassiege** [comment]
(sorry for the delay !! I just noticed that I didn't receive any notification)

Hi
This is indeed a problem in the documentation. The repository to clone is https://github.com/hlassiege/demo-mistral

I'll fix the documentation !

**Comment by hlassiege** [comment]
The documentation has been updated : https://bloggrify.com/introduction/installation
