### ISSUE TITLE
Twitter links to non posts don't work

### ISSUE THREAD

**Issue by IO-Fire** [bloggrify/bloggrify#10]
Hyperlinks inside of markdown and anchor tags to content other than posts are modified, replacing the intended destination

### Example
```markdown
https://x.com/hashtag/Wikipedia20
```

#### Becomes
```
https://twitter.com/x/status/null
```

See [`components/content/prose/ProseA.vue`](https://github.com/bloggrify/bloggrify/blob/main/components/content/prose/ProseA.vue#L63)

## Potential Fix
Increased checks on what the twitter link type is.

**Comment by hlassiege** [comment]
Thanks for the report !

It's fixed in https://github.com/bloggrify/bloggrify/commit/5ae352c1c4d9aafbaa56f5df0e86951d8170f3f2
