### ISSUE TITLE
404 page shows wrong content

### ISSUE THREAD

**Issue by IO-Fire** [bloggrify/bloggrify#11]
When visiting a page that does not exist the rendered page is empty or does not show 404 page.

### Example

[Minimalist Demo](https://minimalist.bloggrify.com/404-test)

[Mistral Demo](https://mistral.bloggrify.com/404-test)

## Potential Fix

Check error handling logic to ensure error page is shown.

**Comment by hlassiege** [comment]
Thanks a lot for the report. 
The Pull request has been merged !
