### ISSUE TITLE
GitHub releases version does not match NPM version

### ISSUE THREAD

**Issue by IO-Fire** [bloggrify/bloggrify#15]
When visiting the GitHub repository page, the version `v1.4.5` does not match the NPM version `1.7.0`.
### Example

[GitHub](https://github.com/bloggrify/bloggrify/releases)

[NPM](https://www.npmjs.com/package/@bloggrify/core)

## Potential Fix

GitHub action to update GitHub releases and NPM after PR merge.

**Comment by hlassiege** [comment]
Hi, thanks for the report

To be honest, I'm not an expert with the release process. I do it manually and I always forgot some steps
I'll try to document it to avoid those kind of errors

**Comment by hlassiege** [comment]
It's a mess, I've created a 1.7.0 version on github
The version 1.4.5, 1.5.0 and 1.6.0 are irrelevant because of my lack of knowledge to the release process. 
But I'll try to add some doc and avoid that in the future
