### ISSUE TITLE
Search shows no results

### ISSUE THREAD

**Issue by IO-Fire** [bloggrify/bloggrify#16]
When visiting a page and using the search feature the results are empty.

### Example

[Mistral Demo](https://mistral.bloggrify.com/)

<img width="701" alt="image" src="https://github.com/user-attachments/assets/9f791983-2658-4d3e-bb01-6dca79c98212">

<img width="678" alt="image" src="https://github.com/user-attachments/assets/d4afbb3e-1dd3-4eca-bcc9-29b13ba2c904">

## Potential Fix

Update logic error in [`server/api/search.ts`](https://github.com/bloggrify/bloggrify/blob/main/server/api/search.ts) to return pages that are not hidden.

**Comment by hlassiege** [comment]
Thanks for the PR.
I'll close this issue
