### ISSUE TITLE
Expand Table of Content with H3 Headers

### ISSUE THREAD

**Issue by Hustler-Am-Limit** [bloggrify/bloggrify#2]
Hi.

I noticed that in your document, you mentioned that only h2 headers are displayed in the table of content inside an article. 

Is there a way to expand this rule to also include h3 headers? I put a lot of time into solving this, with no success. Maybe you can guide us to the right direction 👍🏿?

**Comment by hlassiege** [comment]
(sorry for the late reply, I just noticed that I didn't receive any notification)

Hi,

I can add an option to include H3 headers. The code itself is in Toc.vue

**Comment by hlassiege** [comment]
Now it's possible to display the H3 headers if you use the following configuration to app.config.ts 

```
    toc : {
        showChildren: true,
    },
```
