### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by boid-com** [bloggrify/bloggrify#25]
I'm experienced with Vue development but new to Nuxt. I have the example setup and working correctly using the mistral theme. Trying to customize it, the guide isn't clear about how to setup a new theme. https://bloggrify.com/reference/theming. Does the new theme need to be a standalone module, how do you register the custom theme to be usable? The instructions says a theme is a nuxt module but also just a folder, can I just add a *theme* dir to my project or do I have to break the theme out into it's own independent repo? It would be nice if the instructions were a bit more explicit for nuxt newbies.

**Comment by hlassiege** [comment]
Hi,

Indeed, I'll try to improve the documentation.

To start a new theme, you don't need to create it in a separate module/repository. 
You can start from the the mistral theme and add a new folder "layouts/theme/mylayout"
In order to switch from the mistral theme to the mylayout theme, you just have to modify the name of the theme in the app.config.ts file

A theme should have : 
- a default layout (you can look at the mistral theme to understand how it works)

and that's all, the rest is optional (components, assets, etc...)

**Comment by boid-com** [comment]
When you say "start from the mistral theme" do you mean the mistral theme repo or the mistral demo repo where you have core importing mistral? the mistral theme repo includes package.json and many other things. is it possible to just start with the core/minimalist theme and add a theme folder so that you can have everything in one repo?

**Comment by hlassiege** [comment]
The correct part of the documentation is here : 

https://bloggrify.com/reference/theming#create-a-new-theme

"To create a new theme, you can start with the ["Mistral"](https://github.com/bloggrify/bloggrify-mistral) theme. It is a simple and clean template. You can clone the repository and start modifying it."

indeed, there is also the `minimalist` theme which is simpler to understand. However, this theme is included with the bloggrify core system and if you clone the whole repository (bloggrify), it's harder to understand how to start.

option 1 : you start from the bloggrify/bloggrify-mistral them, you clone it, and you modify it for your own usage, customizing the name, customizing the option etc...
option 2 : you start from scratch. This part is not documented yet, but I'm currently writing this section and it should be available soon. (Maybe in one hour, so you may read both this answer and the updated documentation at the same time)

EDIT : it's available here : https://bloggrify.com/recipes/theme-recipe

**Comment by boid-com** [comment]
Thanks! This new guide is much more clear!
