### ISSUE TITLE
GitHub Issues feature missing on repositories

### ISSUE THREAD

**Issue by IO-Fire** [bloggrify/bloggrify#26]
When viewing repositories in the [bloggrify GitHub organisation](https://github.com/bloggrify) some have the GitHub Issues feature disabled. This prevents issues be filed in the correct place.  

### Example

- [bloggrify/bloggrify-mistral](https://github.com/bloggrify/bloggrify-mistral)
- [bloggrify/demo-mistral](https://github.com/bloggrify/demo-mistral)

## Potential Fix

Enable the feature GitHub Issues in the repositories settings.

**Comment by hlassiege** [comment]
Hi
To be honest, it was done on purpose. But you're right, it's not convenient.
It's enabled again
