### ISSUE TITLE
Embedding of YouTube videos and tweets not working in markdown

### ISSUE THREAD

**Issue by Hustler-Am-Limit** [bloggrify/bloggrify#5]
See own documentation page: https://bloggrify.com/reference/markdown#youtube-and-twitter-embed

**Comment by hlassiege** [comment]
(sorry for the delay, I just noticed that I didn't receive any notification)

Hi,
I'm not sure to understand the bug report. 
I can't reproduce the problem you have. I can see tweets and videos displayed correctly.

![image](https://github.com/hlassiege/bloggrify/assets/666123/25d6dd91-ce0c-460f-b189-0e3aca6ad023)

**Comment by hlassiege** [comment]
ok, found it, this is a problem in the mistral template.
The fix is on its way
