### ISSUE TITLE
How to use the category route

### ISSUE THREAD

**Issue by Shun-Ibiki** [bloggrify/bloggrify#6]
Hi, I just clone this project and simply add categories frontmatter into /content/features.md. 

```
categories:
  - example
```

But, when i try to visit /categories/example, i got `Invalid layout themes-mistral-category selected.` warning.
So, I wonder how the correct way to access this route? Do I need to create my custom theme first?

**Comment by hlassiege** [comment]
Hi,

Could you tell me, what repository did you clone ?

**Comment by hlassiege** [comment]
My first guess, even if I don't know exactly your setup.
I suppose you had cloned the bloggrify repository and started without any theme.
You can start [without a theme and build your own theme](https://bloggrify.com/reference/theming#create-a-new-theme). But this is the hard way. 

The easy way is to start from the mistral theme. 
You can follow the getting started guide to do so : https://bloggrify.com/introduction/installation

**Comment by hlassiege** [comment]
Without further info, I can't help ^^
I'll close this issue and let me know if you still have a problem
