### ISSUE TITLE
Is there any way to integrate bloggrify as a submodule of an existing nuxt+tailwind project?

### ISSUE THREAD

**Issue by cillywill** [bloggrify/bloggrify#7]
integrate bloggrify as a subpath of an existing website,  like  www.example.com/blog.

**Comment by hlassiege** [comment]
Hi 
I think there is 2 questions here : 

- Using Bloggrify as a subfolder is definitely ok. 
You just have to modify the app/baseURL option in the nuxt.config.ts file

- Including Bloggrify in an existing app, might be possible. 
I never tried but you can 
* keep the normal baseURL on /
* Write your content under /content/blog/**/*.md files
* And write your application as usual, using pages, components etc…

Let me know if you want a demo project

**Comment by cillywill** [comment]
I tried including Bloggrify in an existing app, but failed.
Finally  I deployed the blog app as a individual app,  then use cloudflare worker to route traffic from /blog path to this individual app. 
here is the worker script:

```
export default {
	/**
	 * @param {Request} request
	 * @param {Env} env
	 * @param {ExecutionContext} ctx
	 * @returns {Promise<Response>}
	 */
	async fetch(request, env, ctx) {
		const url = new URL(request.url);
		if (url.pathname.startsWith('/blog')) {
		url.hostname = 'xxxxxx.pages.dev'
		url.pathname = url.pathname.replace('/blog', '/')
    		return fetch(url.toString(), request)
		}
		return fetch(request)
	},
};
```

It works now. Thank you for reply. @hlassiege
