### ISSUE TITLE
Post cover images incorrect on social media site

### ISSUE THREAD

**Issue by IO-Fire** [bloggrify/bloggrify#8]
The HTML meta Open Graph tags are using the incorrect attribute `name` instead of `property` in [pages/[...slug].vue](https://github.com/bloggrify/bloggrify/blob/main/pages/%5B...slug%5D.vue#L214) which is used to set the post metadata.
<details><summary>Details</summary>
<p>

## Example

Using the LinkedIn Post Inspector for [Mistral Blog post: Mermaid](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fmistral.bloggrify.com%2Fmermaid) (*requires login to LinkedIn*) would show: 
![image](https://github.com/user-attachments/assets/c061a1e4-cca2-48e1-84e8-4f2a4b42b81d)

### Post Inspector properties
![image](https://github.com/user-attachments/assets/7614798c-2de4-4f75-81d7-6d68f13f3a28)

Instead of the intended post cover: 
![image](https://github.com/user-attachments/assets/79ef64e6-3cd2-4d32-9a95-8136465db898)

</p>
</details> 

## Suggested Fix

Update the Open Graph tags to use the `property` attribute instead of `name`.

Feedback and suggestions are welcome!

**Comment by hlassiege** [comment]
Thanks for the report and the pull request !
